export const iconNames = [
  'search',
  'calculator',
  'grid-view',
  'mail-at-sign',
  'message-add',
  'money-exchange',
  'notification',
  'settings',
  'user-group',
  'money',
  'moneys',
  'chevron-left',
  'chevron-right',
  'chevron-down',
  'import',
  'export',
  'export-2',
  'wallet-add',
  'wallet-minus',
  'dropdown',
  'arrow-left',
  'arrow-right',
  'arrow-right-up',
  'people',
  'personal-card',
  'exchange',
  'message-download',
  'add-circle',
  'minus-circle',
  'file-add',
  'document',
  'arrow-circle-right',
  'plus',
  'delete',
] as const;

export type ISvgIconName = (typeof iconNames)[number];
